alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: ez-tracking-postgres
  db_name: defaultdb
  db_user: doadmin
  engine: PG
  name: ez-tracking-postgres
  production: true
  version: "17"
- cluster_name: ez-tracking-redis
  engine: VALKEY
  name: ez-tracking-redis
  production: true
  version: "8"
domains:
- domain: app.dccderm.com
  type: PRIMARY
envs:
- key: CLAUDE_API_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Z9+4seZ2/IjpBzy3JW3ldVKTRQw98kdP:bjVVOA6AuxgWO0NNUVVrnZFvSuiE9z+04drVzY5brEHtpfW8V3D4Dl23s/cWRZbdI33MbBEnXzRWBHutFrPTkNPmNDZO8DoMJrOwcm0W7E9R9pci5U/3aARNEpngp5mGIOTcukzO5amHlU5MBvlmk9Nvs69hlvA9Qxvnmg==]
- key: EZDERM_PASS
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:HFeB6z5I5mR4CYzsXm+Y6m3m1R2pxEqX:jrSsVllJIhzZQIBJNXM0691VYBnb12rtEhc=]
- key: EZDERM_USER
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:VQilQ9myOMpwmNYDZpueQPn/laETF9i5:khnjcx6ClPZ6vtFoe+oRS/w9SFo89B4=]
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: backend
    match:
      path:
        prefix: /api
  - component:
      name: bull-board
    match:
      path:
        prefix: /bull-board
  - component:
      name: frontend
    match:
      path:
        prefix: /
name: sea-turtle-app
region: nyc
services:
- alerts:
  - operator: GREATER_THAN
    rule: CPU_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: MEM_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: RESTART_COUNT
    value: 10
    window: FIVE_MINUTES
  dockerfile_path: server/Dockerfile
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "5001"
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.HOSTNAME}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.PORT}
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.DATABASE}
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.PASSWORD}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.DATABASE_URL}
  - key: REDIS_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.HOSTNAME}
  - key: REDIS_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.PORT}
  - key: REDIS_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.PASSWORD}
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.DATABASE_URL}
  - key: CORS_ORIGIN
    scope: RUN_AND_BUILD_TIME
    value: https://app.dccderm.com
  - key: DEBUG_AXIOS
    scope: RUN_AND_BUILD_TIME
    value: "false"
  github:
    branch: production
    deploy_on_push: true
    repo: eni9889/ez-tracking-board
  health_check:
    failure_threshold: 3
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    success_threshold: 1
    timeout_seconds: 5
  http_port: 5001
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: backend
  run_command: npm start
  source_dir: /server
- dockerfile_path: server/Dockerfile
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: BULL_BOARD_PORT
    scope: RUN_AND_BUILD_TIME
    value: "3001"
  - key: REDIS_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.HOSTNAME}
  - key: REDIS_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.PORT}
  - key: REDIS_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.PASSWORD}
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.DATABASE_URL}
  github:
    branch: production
    deploy_on_push: true
    repo: eni9889/ez-tracking-board
  health_check:
    failure_threshold: 3
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 10
    success_threshold: 1
    timeout_seconds: 10
  http_port: 3001
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: bull-board
  run_command: npm run bull-board
  source_dir: /server
static_sites:
- build_command: npm ci --no-audit --no-fund && npm run build
  catchall_document: index.html
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: https://app.dccderm.com
  - key: REACT_APP_USE_MOCK_DATA
    scope: BUILD_TIME
    value: "false"
  - key: NODE_ENV
    scope: BUILD_TIME
    value: production
  github:
    branch: production
    deploy_on_push: true
    repo: eni9889/ez-tracking-board
  index_document: index.html
  name: frontend
  output_dir: build
  source_dir: /frontend
workers:
- alerts:
  - operator: GREATER_THAN
    rule: CPU_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: MEM_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: RESTART_COUNT
    value: 10
    window: FIVE_MINUTES
  dockerfile_path: server/Dockerfile
  envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: DB_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.HOSTNAME}
  - key: DB_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.PORT}
  - key: DB_NAME
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.DATABASE}
  - key: DB_USER
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.PASSWORD}
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-postgres.DATABASE_URL}
  - key: REDIS_HOST
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.HOSTNAME}
  - key: REDIS_PORT
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.PORT}
  - key: REDIS_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.PASSWORD}
  - key: REDIS_URL
    scope: RUN_AND_BUILD_TIME
    value: ${ez-tracking-redis.DATABASE_URL}
  - key: DEBUG_AXIOS
    scope: RUN_AND_BUILD_TIME
    value: "false"
  github:
    branch: production
    deploy_on_push: true
    repo: eni9889/ez-tracking-board
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: worker
  run_command: node dist/jobProcessor.js
  source_dir: /server
